### ISSUE TITLE
Error generating schema "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by rawlingsj** [csrwng/origin-schema-generator#2]
I've been trying to generate the schema since yesterday without success.  Not being familiar with go I'm struggling to understand why this is happening.  Stack trace below and I've tried some nil detection but still it fails.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0xa6858]

goroutine 16 [running]:
runtime.panic(0x3cf1c0, 0x655e64)
    /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/panic.c:279 +0xf5
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getStructProperties(0xc20803fa40, 0x72b1d8, 0x3ce360, 0xa4a09679a95c2858)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:226 +0x398
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).generateObjectDescriptor(0xc20803fa40, 0x72b1d8, 0x3ce360, 0xc208090f20)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:239 +0x7a
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getPropertyDescriptor(0xc20803fa40, 0x72b1d8, 0x3ce360, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:193 +0x867
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getStructProperties(0xc20803fa40, 0x72b1d8, 0x3fb280, 0xc8401749c5812589)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:216 +0x14d
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).generateObjectDescriptor(0xc20803fa40, 0x72b1d8, 0x3fb280, 0xc208091390)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:239 +0x7a
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getPropertyDescriptor(0xc20803fa40, 0x72b1d8, 0x3fb280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:193 +0x867
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getPropertyDescriptor(0xc20803fa40, 0x72b1d8, 0x2eb9c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:174 +0x61c
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getStructProperties(0xc20803fa40, 0x72b1d8, 0x3e2220, 0xde7321736c9502c)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:216 +0x14d
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).generateObjectDescriptor(0xc20803fa40, 0x72b1d8, 0x3e2220, 0xc208091920)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:239 +0x7a
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getPropertyDescriptor(0xc20803fa40, 0x72b1d8, 0x3e2220, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:193 +0x867
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getStructProperties(0xc20803fa40, 0x72b1d8, 0x3afc00, 0x5ea2005eec88499a)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:216 +0x14d
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).generateObjectDescriptor(0xc20803fa40, 0x72b1d8, 0x3afc00, 0xc208091d90)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:239 +0x7a
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getPropertyDescriptor(0xc20803fa40, 0x72b1d8, 0x3afc00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:193 +0x867
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getStructProperties(0xc20803fa40, 0x72b1d8, 0x3d1fe0, 0xdae2f90eead3ff23)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:216 +0x14d
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).generateObjectDescriptor(0xc20803fa40, 0x72b1d8, 0x3d1fe0, 0xc208092200)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:239 +0x7a
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getPropertyDescriptor(0xc20803fa40, 0x72b1d8, 0x3d1fe0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:193 +0x867
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getStructProperties(0xc20803fa40, 0x72b1d8, 0x3e2e20, 0x1318c42b48ab6fb6)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:216 +0x14d
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).generateObjectDescriptor(0xc20803fa40, 0x72b1d8, 0x3e2e20, 0xc208092670)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:239 +0x7a
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getPropertyDescriptor(0xc20803fa40, 0x72b1d8, 0x3e2e20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:193 +0x867
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getPropertyDescriptor(0xc20803fa40, 0x72b1d8, 0x2ecf80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:174 +0x61c
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getStructProperties(0xc20803fa40, 0x72b1d8, 0x3c2b60, 0xdf7ba291e2a3daab)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:216 +0x14d
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).generateObjectDescriptor(0xc20803fa40, 0x72b1d8, 0x3c2b60, 0xc208092c00)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:239 +0x7a
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getPropertyDescriptor(0xc20803fa40, 0x72b1d8, 0x3c2b60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:193 +0x867
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).getStructProperties(0xc20803fa40, 0x72b1d8, 0x400d60, 0x3)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:216 +0x14d
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).generateObjectDescriptor(0xc20803fa40, 0x72b1d8, 0x400d60, 0x6)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:239 +0x7a
github.com/csrwng/origin-schema-generator/pkg/schemagen.(*schemaGenerator).generate(0xc20803fa40, 0x72b1d8, 0x400d60, 0xc208094690, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:110 +0x1b6
github.com/csrwng/origin-schema-generator/pkg/schemagen.GenerateSchema(0x72b1d8, 0x400d60, 0xc2080933a8, 0xc, 0xc, 0xc208094690, 0x65f640, 0x0, 0x0)
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/pkg/schemagen/generate.go:23 +0x7e
main.main()
    /Users/jamesrawlings/go/src/github.com/csrwng/origin-schema-generator/cmd/generate/generate.go:64 +0x511

goroutine 19 [finalizer wait]:
runtime.park(0x150b0, 0x659478, 0x657f29)
    /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0x659478, 0x657f29)
    /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
    /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
    /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1445

goroutine 20 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x65b6e0)
    /Users/jamesrawlings/code/kubernetes/src/github.com/golang/glog/glog.go:879 +0x75
created by github.com/golang/glog.init·1
    /Users/jamesrawlings/code/kubernetes/src/github.com/golang/glog/glog.go:410 +0x2b2

goroutine 17 [syscall]:
runtime.goexit()
    /usr/local/Cellar/go/1.3.3/libexec/src/pkg/runtime/proc.c:1445
```

**Comment by rawlingsj** [comment]
Closed, I was running the generate under go/bin and not the one I was compiling.

**Comment by jimmidyson** [comment]
@rawlingsj - can you reopen please as sadly this still happens with latest kubernetes source. Narrowed it down to generating stuff for https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/resource/quantity.go#L86-L94 which has been added recently. Not sure why & my lack of go foo hasn't helped in finding a solution.

**Comment by rawlingsj** [comment]
Yeah thanks for confirming @jimmidyson.

@csrwng if the type prop.JSONReferenceDescriptor is nil, as it is in the struct that @jimmidyson has linked to we get the stack trace above. ref https://github.com/csrwng/origin-schema-generator/blob/master/pkg/schemagen/generate.go#L219

Is this an issue with the Kubernetes type or should the generator be updated to handle it?

**Comment by csrwng** [comment]
@jimmidyson @rawlingsj - the generator can be fixed so it can handle it. Sorry I've been distracted with other issues, but I'll try to update things by eod today.

**Comment by rawlingsj** [comment]
@csrwng no worries at all, I've enjoyed the last day or so with Go and know I need to understand more.  I'm interested to see how to resolve it as coming from a java background I realise I've a lot to learn.

**Comment by csrwng** [comment]
The issue was that as @jimmidyson pointed out, in https://github.com/GoogleCloudPlatform/kubernetes/blob/master/pkg/api/resource/quantity.go#L86-L94 there is an anonymous field that is not a struct, it's actually of type string. My reflection code was expecting all anonymous fields to be structs. I've now delivered a fix: https://github.com/csrwng/origin-schema-generator/commit/bcd458d3e9ccf1dd952265c35cc0a675f817ac67 and updated Godeps to the latest origin and kubernetes versions.

**Comment by csrwng** [comment]
I also added references to the new packages referenced in Kubernetes API - you may want to do the same in your version of the code. Otherwise they get an empty Java package -> https://github.com/csrwng/origin-schema-generator/commit/05ddd65a3ce524c98aa6fa53726db0136b638533

**Comment by rawlingsj** [comment]
Many thanks @csrwng, that's working and I have an up-to-date schema being generated.
